# Generated by Django 2.0.2 on 2018-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleStick_4H_ETH_USDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2018-01-23 15:55')),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CandleStick',
        ),
    ]
