# Generated by Django 2.0.2 on 2018-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0004_candlestick_4h_eth_usdt_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleStick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2018-01-23 15:55')),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
            ],
        ),
    ]
