# Generated by Django 2.0.2 on 2018-11-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0006_auto_20181107_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo2',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo2',
        ),
    ]
