# Generated by Django 2.0.2 on 2018-11-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0007_auto_20181107_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleStick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_period', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default='2018-01-23 15:55')),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_number', models.PositiveIntegerField()),
                ('buy', models.BooleanField()),
                ('sell', models.BooleanField()),
                ('stock_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.CandleStick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='CandleStick_4H_ETH_USDT',
        ),
    ]
