# Generated by Django 2.0.2 on 2018-11-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_app', '0008_auto_20181128_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlestick',
            name='currency_period',
        ),
        migrations.AddField(
            model_name='candlestick',
            name='pair',
            field=models.CharField(default='USDT_ETH', max_length=20),
        ),
        migrations.AddField(
            model_name='candlestick',
            name='period',
            field=models.CharField(default='KLINE_INTERVAL_4HOUR', max_length=20),
        ),
    ]
